### ISSUE TITLE
steam-crypto - Object #<Object> has no method 'publicEncrypt'

### ISSUE THREAD

**Issue by robiXxu** [DoctorMcKay/node-steam-client#3]
```
home/robixxu/root/steamtest/node_modules/@doctormckay/steam-crypto/index.js:25
        var cryptedSessionKey = Crypto.publicEncrypt(g_PubkeySystem, Buffer.concat([s
                                       ^
TypeError: Object #<Object> has no method 'publicEncrypt'
    at Object.exports.generateSessionKey (/home/robixxu/root/steamtest/node_modules/@doctormckay/steam-crypto/index.js:25:33)
    at CMClient.handlers.(anonymous function) (/home/robixxu/root/steamtest/node_modules/steam-client/lib/cm_client.js:342:31)
    at CMClient._netMsgReceived (/home/robixxu/root/steamtest/node_modules/steam-client/lib/cm_client.js:260:24)
    at TCPConnection.emit (events.js:95:17)
    at TCPConnection._readPacket (/home/robixxu/root/steamtest/node_modules/steam-client/lib/tcp_connection.js:73:7)
    at TCPConnection.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at TCPConnection.Readable.push (_stream_readable.js:128:10)
```

**Comment by robiXxu** [comment]
same error on steam-user.

**Comment by DoctorMcKay** [comment]
>Requires Node.js v4.1.1 or later.

**Comment by robiXxu** [comment]
Thank you!
